name: bayes_rules
channels:
  - conda-forge
dependencies:
  - python
  - pandas
  - requests
  - pyreadr
  - seaborn
  - pip
  - mkl-service
  - scipy
  - arviz
  - pymc3
  - ipykernel
  - pip:
    - watermark